### ISSUE TITLE
编译路径是反斜杠\

### ISSUE THREAD

**Issue by cz2013** [tjuking/gulp-resolve-path#1]
你好，使用你的插件编译html，js和css和图片的引用路径都是反斜杠\
<script type="text/javascript" src="\src\views\common\js\flexible.js"></script>

**Comment by tjuking** [comment]
@cz2013 你是windows系统是吧？

**Comment by cz2013** [comment]
我了解了，在window和linux上路径斜杠是有这个问题。我已经通过其他方式解决了~~谢谢哈
